services:
  - type: web
    name: videomax-frontend
    env: static
    buildCommand: echo "No build required for static files"
    staticPublishPath: ./public
    routes:
      - type: rewrite
        source: /admin
        destination: /admin.html
      - type: rewrite
        source: /users
        destination: /users.html
      - type: rewrite
        source: /
        destination: /users.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
    envVars:
      - key: NODE_ENV
        value: production