backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "users"
    label: "Users"
    folder: "content/users"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Role", name: "role", widget: "select", options: ["user", "admin"]}
      - {label: "Active", name: "isActive", widget: "boolean", default: true}
      - {label: "Created Date", name: "createdAt", widget: "datetime"}
      - {label: "Profile Image", name: "profileImage", widget: "image", required: false}
      - {label: "Bio", name: "bio", widget: "text", required: false}

  - name: "videos"
    label: "Videos"
    folder: "content/videos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Video URL", name: "videoUrl", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Status", name: "status", widget: "select", options: ["draft", "published", "private"]}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Views", name: "views", widget: "number", default: 0}
      - {label: "Likes", name: "likes", widget: "number", default: 0}
      - {label: "Duration", name: "duration", widget: "number"}
      - {label: "Upload Date", name: "createdAt", widget: "datetime"}
      - {label: "User ID", name: "userId", widget: "string"}

  - name: "analytics"
    label: "Analytics"
    folder: "content/analytics"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Total Views", name: "totalViews", widget: "number"}
      - {label: "Total Users", name: "totalUsers", widget: "number"}
      - {label: "Total Videos", name: "totalVideos", widget: "number"}
      - {label: "Active Users", name: "activeUsers", widget: "number"}
      - {label: "New Signups", name: "newSignups", widget: "number"}
      - {label: "Video Uploads", name: "videoUploads", widget: "number"}

  - name: "settings"
    label: "Platform Settings"
    folder: "content/settings"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Setting Name", name: "name", widget: "string"}
      - {label: "Setting Value", name: "value", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "select", options: ["general", "security", "media", "notifications"]}
      - {label: "Active", name: "isActive", widget: "boolean", default: true}

  - name: "ads"
    label: "Advertisements"
    folder: "content/ads"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Ad Title", name: "title", widget: "string"}
      - {label: "Ad Content", name: "content", widget: "text"}
      - {label: "Ad Image", name: "image", widget: "image", required: false}
      - {label: "Target URL", name: "targetUrl", widget: "string", required: false}
      - {label: "Position", name: "position", widget: "select", options: ["header", "sidebar", "footer", "inline"]}
      - {label: "Active", name: "isActive", widget: "boolean", default: true}
      - {label: "Start Date", name: "startDate", widget: "datetime"}
      - {label: "End Date", name: "endDate", widget: "datetime"}
      - {label: "Impressions", name: "impressions", widget: "number", default: 0}
      - {label: "Clicks", name: "clicks", widget: "number", default: 0}